### ISSUE TITLE
Libraries Issue

### ISSUE THREAD

**Issue by Jasiniok** [fromhellside/s0beit_Project-Attack#1]
Hello, I suck at coding/programming right now and am seeking on learning, if possible could you link me up with a quick guide onto how to set up the libraries required to compile this script? Or a quick guide on how can I compile it by myself? 
I fixed most of the issues I had by googling, trying out and stuff, but I can't seem to fix some libraries errors even if I try whatever methods.
I'm currently running VS 2019, and the errors I'm having are as follows: 
Code LNK1181 - cannot open input file 'bass.lib' - I fixed this one
Code LNK1181 - cannot open input file 'detours.lib' - can't proceed through this one tho even though I downloaded them and included them in C++ Additional library directories and stuff.
Thanks in the meantime!

**Comment by Jasiniok** [comment]
Alright, I fixed the libraries issue, compiled/build the project successfully - I didn't have any errors nor warnings, but now I'm struggling in-game, I'm not able to move or anything (neither press f11, f2 or anything), the hud appears black (money and stuff, not the chat), I guess this could be from a missing folder, mod_sa.ini or Rapid....-.ini issue, some help? Or if possible, could you send me the .ini (including the folder name) and stuff that this cheat uses? Thank you! 
![image](https://user-images.githubusercontent.com/48657286/115574877-50ed0d80-a2c2-11eb-8e1e-90592909048c.png)

**Comment by RapidFireX** [comment]
> Alright, I fixed the libraries issue, compiled/build the project successfully - I didn't have any errors nor warnings, but now I'm struggling in-game, I'm not able to move or anything (neither press f11, f2 or anything), the hud appears black (money and stuff, not the chat), I guess this could be from a missing folder, mod_sa.ini or Rapid....-.ini issue, some help? Or if possible, could you send me the .ini (including the folder name) and stuff that this cheat uses? Thank you!
> ![image](https://user-images.githubusercontent.com/48657286/115574877-50ed0d80-a2c2-11eb-8e1e-90592909048c.png)
which samp version u have selected in SelectSAMPVersion header? you need to choose your client version and compile it again and yes, theres some folders are missing you need to change the names of folders/ini files.

**Comment by Jasiniok** [comment]
Seems like you deleted that comment, I fixed it by renaming all of the folders and .ini-s (I got the default s0beit's .ini and then renamed it), I added the enable anttweakbar menu in the .ini, and added a key, but now I'm not able to activate the anttweakbar menu, what could be wrong? I'm sorry, I know I'm such a newbie lol

**Comment by Jasiniok** [comment]
Fixed it, if anyone else encounters this issue, it has a different anttweakbar setting: 
Thank you for the guidance in the previous comment, I hope I can get to working on the project further now :)
AntTweakBar_Use = true
AntTweakBar_Menu_Key = F2

**Comment by Jasiniok** [comment]
Fixed everything, got the .ini manually from the ini header & css
